"use client"; // useRoute hook is only available in client components
// this will dispay the conference data which is currently hardcoded from the mocks folder
// we can use exisiting styles etc for this aswell
import { mockConferences } from "@/mocks/conference";
import { useRouter } from "next/navigation"; // this will allow us to get the conference id from the url
// 404 page if conference not found
import { notFound } from "next/navigation";
import React from "react";

interface ConferenceDetailsPageProps {
  params: Promise<{
    id: string;
  }>;
}

export default function ConferenceDetailsPage({ params }: ConferenceDetailsPageProps) {
    const { id } = React.use(params);

    const conference = mockConferences.find(conf => conf.id === id);
    const router = useRouter();

    if (!conference) {
        notFound();
    }

    return (
        // styles / layout generated by ai
    <main className="max-w-2xl mx-auto p-8">
      <button
        onClick={() => router.back()}
        className="mb-4 underline text-blue-700"
      >
        ← Back to Events
      </button>
      <img
        src={conference.imageUrl}
        alt={conference.name}
        className="rounded-lg mb-4 w-full h-64 object-cover"
      />
      <h1 className="text-2xl font-bold mb-2">{conference.name}</h1>
      <div className="mb-2 text-gray-600">
        {conference.location} · {conference.date}
      </div>
      <div className="mb-4">{conference.description}</div>
      <div className="flex flex-wrap gap-2 mb-4">
        {conference.category.map(cat => (
          <span key={cat} className="bg-blue-100 text-blue-800 rounded px-2 py-1 text-xs">{cat}</span>
        ))}
      </div>
      <button className="bg-blue-600 text-white px-4 py-2 rounded hover:bg-blue-800">
        Register
      </button>
    </main>
  );

}



